### ISSUE TITLE
Armenia does not have region assigned 

### ISSUE THREAD

**Issue by gradoj** [gradoj/hplans#10] opened 2021-12-15 18:03 UTC
csv has Armenia as EU868 and geojson appears to be present but no lorawan-h3 hexes
![image](https://user-images.githubusercontent.com/7544765/146240792-4b26570d-272f-4dac-bea9-d264614057c3.png)

**Comment by gradoj** [comment] 2021-12-16 16:07
The geojson polygon is present
![image](https://user-images.githubusercontent.com/7544765/146406730-c15f17af-8c8f-466b-80ea-459e8d4e9ede.png)

**Comment by Arayikhurshudyan** [comment] 2021-12-17 18:16
The problem still didn't resolved. All miners didn't do any activities(witness or beaconing).

**Comment by gradoj** [comment] 2021-12-18 19:51
Armenia is in the EU868 geojson polygons but does not appear in the h3idx hexes that went in the miner for pocv11. I regenerated them and it is correct. This will get updated next miner release. Looks like the lorawan-h3 needed an update.
![image](https://user-images.githubusercontent.com/7544765/146653969-c2246b20-ac7e-44f8-b482-7b4624c0c1e6.png)
This can be closed after it is confirmed to have made it into https://github.com/helium/lorawan-h3/tree/main/serialized

**Comment by KryptoMyner** [comment] 2021-12-19 20:31
Very good news!  Thank you @gradoj!

**Comment by Arayikhurshudyan** [comment] 2021-12-19 21:08
> Armenia is in the EU868 geojson polygons but does not appear in the h3idx hexes that went in the miner for pocv11. I regenerated them and it is correct. This will get updated next miner release. Looks like the lorawan-h3 needed an update. ![image](https://user-images.githubusercontent.com/7544765/146653969-c2246b20-ac7e-44f8-b482-7b4624c0c1e6.png) This can be closed after it is confirmed to have made it into https://github.com/helium/lorawan-h3/tree/main/serialized

Hi gradoj. Thank you for your work. When the new firmware will be available? Are there a chance that it will be in next week ?Because we earn nothing after POC11 activation. Thnak you.

**Comment by gradoj** [comment] 2022-01-17 04:20
This should be addressed. Someone confirm and this can be closed.

**Comment by Arayikhurshudyan** [comment] 2022-01-17 18:13
I can confirm that it works. Thank you.

**Comment by KryptoMyner** [comment] 2022-01-17 18:53
Yes, Armenian miners are witnessing now.  Thank you!

**Closed** 2022-01-17 19:11 UTC
